name = "vanilla_latest"
mc_version = "1.20.4"

[jar]
type = "paper"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true
preset_flags = "aikars"

[[plugins]]
type = "ghrel"
repo = "playit-cloud/playit-minecraft-plugin"
tag = "latest"
asset = "playit-minecraft-plugin.jar"

[options]
upload_to_mclogs = false
